### ISSUE TITLE
autogen error

### ISSUE THREAD

**Issue by skidoo23** [DaveDavenport/gmpc#15]
Ubuntu 19.04 (64 bit) and GMPC from git.

$ ./autogen.sh
(...)
checking for libmpd... no
configure: error: Package requirements (libmpd >= 11.8.90) were not met:

Requested 'libmpd >= 11.8.90' but version of libmpd is 0.20.0

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libmpd_CFLAGS
and libmpd_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Altering configure.ac to
(...)
# libmpd
PKG_CHECK_MODULES([libmpd], libmpd >= 0.20.0)
AC_SUBST(libmpd_LIBS)
AC_SUBST(libmpd_CFLAGS)
(...)

results in
(...)
Tools/gmpc-auto-reset-priority.c: In function ‘gmpc_tools_auto_reset_priority_status_changed’:
Tools/gmpc-auto-reset-priority.c:113:14: error: ‘mpd_Song’ {aka ‘struct _mpd_Song’} has no member named ‘priority’
    if (_tmp2_->priority > 0) {
              ^~
Tools/gmpc-auto-reset-priority.c:116:5: warning: implicit declaration of function ‘mpd_playlist_set_priority’; did you mean ‘mpd_playlist_get_song’? [-Wimplicit-function-declaration]
     mpd_playlist_set_priority (server, _tmp3_->id, 0);

Any help kindly accepted.

**Comment by DaveDavenport** [comment]
Install libmpd 11.8.90.  

The dependency on that version is in the configure.ac file for a reason.

**Comment by skidoo23** [comment]
Thanks for info :) GMPC build succeeded. Case closed.
