### ISSUE TITLE
Cover file name for GMPC to read from album directory

### ISSUE THREAD

**Issue by TheChymera** [DaveDavenport/gmpc#19]
How should I name a picture file if I want GMPC to read it as the album cover from the directory itself?

Currently, somehow the cover fetching plugin fails because there's nonstandard characters in the album name. I have the cover as Cover.jpg in the album dir, and I was thinking it would work just like that --- but it doesn't.

**Comment by DaveDavenport** [comment]
version?

**Comment by TheChymera** [comment]
11.8.16

**Comment by DaveDavenport** [comment]
To summarize  irc chat:

* Make sure right path to directory is set in preferences.
* Icons are cached, so right click reload you get the latest version.
* glyr is used to fetch, you could check its spec for the exact syntax: https://github.com/sahib/glyr
It might have changed in the past years.

**Comment by TheChymera** [comment]
@DaveDavenport thanks, that worked :)
