### ISSUE TITLE
[FTBS] gmpc latest r.28e1441f is missing file "po/Makefile.in.in"

### ISSUE THREAD

**Issue by Corin-EU** [DaveDavenport/gmpc#21]
Upon git cloning the latest gmpc repository revision r.28e1441f, and running configure, the configure script fails with the error message

              config.status: error: cannot find input file: `po/Makefile.in.in'

The file is not present in the repository.  Copying this file from the gmpc 0.18.6 archive tar file, configuration completes and gmpc can be successfully built and installed.

This missing file  "po/Makefile.in.in"  should be added to the repository.

**Comment by DaveDavenport** [comment]
It is not missing, glib-gettextize generates this file.

**Comment by DaveDavenport** [comment]
Fresh clone still compiles and runs fine for me:

```bash
./src/gmpc -v
Gnome Music Player Client
Copyright 2003-2014 Qball Cow

Tagline                  : All hail the Greg
Version                  : 11.8.90
Revision                 : 28e1441f
```

**Comment by Corin-EU** [comment]
There is no mention of glib-gettextize  in the configure script.

So how do your expect the file to be generated before configure runs?

**Comment by DaveDavenport** [comment]
there is no configure file in the repository, this gets generated by `autogen.sh` script.
When gmpc was written/maintained this was very standard for gnome/gtk applications.

**Comment by Corin-EU** [comment]
Yes because the procedure is

clone repository

autoreconf -fiv  --> to generate configure

configure  --> to generate makefiles

make

**Comment by DaveDavenport** [comment]
That is not the procedure for gmpc.

GMPC is unmaintained, I have no idea what you are trying to achieve.
