### ISSUE TITLE
[Question]  future of gmpc-plugins relative to this gmpc v11.8.90

### ISSUE THREAD

**Issue by Corin-EU** [DaveDavenport/gmpc#22]
I had successfully built and installed the libmpd and gmpc and gmpc-plugins for v11.8.16 and a couple of other plugins which had not succumbed to bitrot due to library version changes.   When I tried building yet another one from the ancient list at the GMPC Fandom site (apparently the "official"site for GMPC), it said I needed to use gmpc v11.8.90 which resulted in a web search leading to this repository for the v11.8.90 version.

Having built and installed the v11.8.90 libmpd and gmpc, I am now unable to build the gmpc-plugins because this gmpc uses Gtk 3.0 and hence the build error message 

                                      error: unknown type name ‘GtkGrid’

because gmpc-plugins pulls in gmpc/plugin.h (which is Gtk 3.0) but gmpc-plugins is using Gtk 2.0 headers.

So the question is, is there a gmpc-plugins compatible with this gmpc v11.8.90, and if not, will you ever consider maintaining the gmpc-plugins for use with this version, or should users of gmpc just stick with v11.8.16 if they want to carry on using the plugins that gmpc-plugins provides?

**Comment by DaveDavenport** [comment]
GMPC has been unmaintained for years, gmpc-plugins for even longer.
What works works, what doesn't work doesn't.  It is what it is.
